language: node_js
node_js:
- '11'
deploy:
  provider: heroku
  api_key:
    secure: WML4Ln01vX9TI/I4+KxVjch/4WJCbymy81jFTr+jXaJImeoSVMo1eA5SzIo/7zbPc8ICk1Loj1yzhfSwLXQzCTlbS0PZwc1Zd3V3AyUARoQzqV3N59sV56tUoOrNjla5aMs3OF26f9EKl0kku5XgfhlQ4jW4vL0DAeH5zmJkrZMQDRnI5B+60sChBWIZYZ0nJ47ZHwNKj3hLpIb+UrcxbX2Mdtj1QnzVV49BvaUyFlkoONMPQV9jDko0qu9jG/kKYWesENBntE9z4q3U6f0VLyNe+sCyQxTuS6sVTQTzNT4nSBv3ds8qQAFeJe+0Ou3cGCiCT0QsZn9We5O79W1EG5k+qgON9YV/v1x2FcPqlmqa9sLW9SuOqUdipN0VvrUDwVvKIvawhvObw9aMbazJsMZ08c1p9Q58iL7NebHZ1GuAtYYZTaqEL8Oaa1tQn0oavlRdEQ/aKAbEPya/oFDRkrCwbldf5+ch8Mdp/hKaGlfQuDL+S4NeHOrHyJ1tww909H70Z9LCUnEnPkJkrdhZTpFYkJL4fMwayL6GDOc/4deLPdFH2MbqQQfKSt3HzBHrXIDTCzkSqlMv35s6gh/DJUswxm+YoTd9pF7wOXjEU45UrCOCbSOOg3Md/Z8Jn6U3V4atPHRgs7XrH95a5klLoBjAHrWzqD0mTsFDqizGIZc=
  app: durak26
